package com.everest.userinfo

const val USERNAME = "USERNAME"
const val EMAIL = "EMAIL"
const val PHONE_NUMBER = "PHONE_NUMBER"
const val PINCODE = "PINCODE"
const val ADDRESS = "ADDRESS"
const val VALIDATE_BUTTON = "VALIDATE_BUTTON"
const val CONFIRM_BUTTON = "CONFIRM_BUTTON"
const val CANCEL_BUTTON = "CANCEL_BUTTON"
const val UPDATE_HEADER_TEXT = "Update your Details"
const val DETAILS_HEADER_TEXT = "Your Details!"
const val HEADER_TEXT = "HEADER_TEXT"
const val EMAIL_TOAST_MESSAGE = "Email is not valid"
const val PHONE_NUMBER_TOAST_MESSAGE = "Phone number shouldn't be less than 10"
const val PINCODE_TOAST_MESSAGE = "Pincode shouldn't be less than 6"
const val FIELD_REQUIRED_TOAST_MESSAGE = " field is required"